"""
Bullish Founder Radar — master people list for the quarterly NinjaPear poll.

Four tiers, ~290 unique people across the biggest consumer brand exits.
Used by the quarterly founder radar poll (POST /api/admin/founder-radar-poll/run).

Cost: 3 credits / person (~$0.03) via NinjaPear /api/v2/employee/profile.
"""

# ── Parent companies we skip for "still_at_brand" / "advisory" detection ─────

_PARENT_COS = frozenset([
    "pepsi", "pepsico", "unilever", "coca-cola", "cocacola", "nestlé", "nestle",
    "kraft", "heinz", "mars", "procter", "gamble", "colgate", "l'oreal", "loreal",
    "estee", "lauder", "lvmh", "puig", "apple", "crocs", "gap", "lululemon",
    "walmart", "amazon", "meta", "google", "microsoft",
])

# ── Brand → website URL mapping for NinjaPear (URLs resolve better than names) ─

BRAND_URLS = {
    "On Running":          "https://www.on.com",
    "Poppi":               "https://drinkpoppi.com",
    "SmartSweets":         "https://smartsweets.com",
    "Hello Products":      "https://helloproducts.com",
    "Primal Kitchen":      "https://primalkitchen.com",
    "Glossier":            "https://www.glossier.com",
    "Catalina Crunch":     "https://catalinacrunch.com",
    "Moon Juice":          "https://moonjuice.com",
    "Super Coffee":        "https://drinksupercoffee.com",
    "Liquid Death":        "https://liquiddeath.com",
    "Dollar Shave Club":   "https://www.dollarshaveclub.com",
    "Athleta":             "https://www.athleta.gap.com",
    "Honest Company":      "https://www.honest.com",
    "Chamberlain Coffee":  "https://chamberlaincoffee.com",
    "Gymshark":            "https://www.gymshark.com",
    "HeyDude":             "https://www.heydude.com",
    "Beats":               "https://www.beatsbydre.com",
    "Daily Harvest":       "https://www.daily-harvest.com",
    "Outdoor Voices":      "https://www.outdoorvoices.com",
    "DECIEM":              "https://deciem.com",
    "BarkBox":             "https://www.barkbox.com",
    "David Protein":       "https://davidprotein.com",
    "Parachute":           "https://www.parachutehome.com",
    "Whoop":               "https://www.whoop.com",
    "Alo Yoga":            "https://www.aloyoga.com",
    "Celsius":             "https://www.celsius.com",
    "Chobani":             "https://www.chobani.com",
    "Chewy":               "https://www.chewy.com",
    "Peloton":             "https://www.onepeloton.com",
    "e.l.f. Beauty":       "https://www.elfcosmetics.com",
    "Warby Parker":        "https://www.warbyparker.com",
    "BodyArmor":           "https://www.drinkbodyarmor.com",
    "Vuori":               "https://vuoriclothing.com",
    "Oura":                "https://ouraring.com",
    "Kind Snacks":         "https://www.kindsnacks.com",
    "Fabletics":           "https://www.fabletics.com",
    "Figs":                "https://www.wearfigs.com",
    "Allbirds":            "https://www.allbirds.com",
    "Skims":               "https://skims.com",
    "Therabody":           "https://www.therabody.com",
    "Savage X Fenty":      "https://www.savagex.com",
    "Rare Beauty":         "https://www.rarebeauty.com",
    "Bombas":              "https://bombas.com",
    "NotCo":               "https://notco.com",
    "Ruggable":            "https://ruggable.com",
    "Magic Spoon":         "https://magicspoon.com",
    "Harry's":             "https://harrys.com",
    "The Farmer's Dog":    "https://www.thefarmersdog.com",
    "Chomps":              "https://www.chomps.com",
    "Athletic Brewing":    "https://athleticbrewing.com",
    "Quest Nutrition":     "https://www.questnutrition.com",
    "AG1":                 "https://drinkag1.com",
    "Cirkul":              "https://www.cirkul.com",
    "Rothy's":             "https://rothys.com",
    "Eight Sleep":         "https://www.eightsleep.com",
    "Article":             "https://www.article.com",
    "Nom Nom":             "https://nomnomnow.com",
    "True Classic":        "https://trueclassic.com",
    "HexClad":             "https://hexclad.com",
    "Ritual":              "https://ritual.com",
    "Nutrafol":            "https://nutrafol.com",
    "Kodiak Cakes":        "https://kodiakcakes.com",
    "Reformation":         "https://www.thereformation.com",
    "Brooklinen":          "https://www.brooklinen.com",
    "Quip":                "https://www.getquip.com",
    "Lovevery":            "https://lovevery.com",
    "Simple Mills":        "https://www.simplemills.com",
    "Huel":                "https://huel.com",
    "Banza":               "https://eatbanza.com",
    "Liquid I.V.":         "https://www.liquid-iv.com",
    "Once Upon a Farm":    "https://onceuponafarmorganics.com",
    "Our Place":           "https://fromourplace.com",
    "MeUndies":            "https://www.meundies.com",
    "Cuts Clothing":       "https://cutsclothing.com",
    "Seed":                "https://seed.com",
    "Caraway":             "https://www.carawayhome.com",
    "Wild":                "https://wearewild.com",
    "Graza":               "https://graza.co",
    "Magic Mind":          "https://magicmind.com",
    "Perfect Bar":         "https://www.perfectbar.com",
    "Burrow":              "https://burrow.com",
    "Lalo":                "https://www.babybrandlalo.com",
    "Mid-Day Squares":     "https://mds.ca",
    "Cocofloss":           "https://cocofloss.com",
    "Native":              "https://nativecos.com",
    "Marine Layer":        "https://www.marinelayer.com",
    "Manscaped":           "https://www.manscaped.com",
    "Mirror":              "https://www.mirror.co",
    "RxBar":               "https://www.rxbar.com",
    "CAULIPOWER":          "https://eatcaulipower.com",
    "Hint Water":          "https://www.drinkhint.com",
    "TOMS":                "https://www.toms.com",
    "Bonobos":             "https://bonobos.com",
    "Honest Tea":          "https://www.honesttea.com",
    "JUST":                "https://www.ju.st",
    "Hungryroot":          "https://www.hungryroot.com",
    "Lemon Perfect":       "https://lemonperfect.com",
    "care/of":             "https://takecareof.com",
    "Fly by Jing":         "https://flybyjing.com",
    "Alani Nu":            "https://alaninu.com",
    "Olipop":              "https://drinkolipop.com",
    "Hims":                "https://www.forhims.com",
    "Rent the Runway":     "https://www.renttherunway.com",
    "Stitch Fix":          "https://www.stitchfix.com",
    "Thrive Market":       "https://thrivemarket.com",
    "Charlotte Tilbury":   "https://www.charlottetilbury.com",
    "Wild One":            "https://wildone.com",
    "KRAVE Jerky":         "https://kravejerky.com",
    "Casper":              "https://casper.com",
    "ILIA Beauty":         "https://www.iliabeauty.com",
    "Good Culture":        "https://www.goodculture.com",
    "Ollie":               "https://myollie.com",
    "JOLIE":               "https://jolieskinco.com",
    "Nasty Gal":           "https://www.nastygal.com",
    "Birchbox":            "https://www.birchbox.com",
    "Adore Me":            "https://www.adoreme.com",
    "Plated":              "https://www.plated.com",
    "Sweetgreen":          "https://www.sweetgreen.com",
    "Stasher":             "https://stasherbag.com",
    "Bloom Nutrition":     "https://bloomnu.com",
    "Away":                "https://www.awaytravel.com",
    "Bala":                "https://ba.la",
    "Create & Cultivate":  "https://createcultivate.com",
    "House of Wise":       "https://houseofwise.com",
    "Filament":            "https://filamentathletic.com",
}


# ── The four tiers ────────────────────────────────────────────────────────────

_DEPARTURES = [
    ("Martin Hoffmann",    "On Running"),
    ("Marc Maurer",        "On Running"),
    ("Allison Ellsworth",  "Poppi"),
    ("Stephen Ellsworth",  "Poppi"),
    ("Tara Bosch",         "SmartSweets"),
    ("Craig Dubitsky",     "Hello Products"),
    ("Morgan Zanotti",     "Primal Kitchen"),
    ("Kyle Leahy",         "Glossier"),
    ("Nikki Neuburger",    "Glossier"),
    ("Julie Bowerman",     "Glossier"),
    ("Krishna Kaliannan",  "Catalina Crunch"),
    ("Nina Fuhrman",       "Moon Juice"),
    ("Tyler Ricks",        "Super Coffee"),
    ("John Shea",          "Liquid Death"),
    ("Jason Goldberger",   "Dollar Shave Club"),
    ("Sally Gilligan",     "Athleta"),
    ("Nancy Green",        "Athleta"),
    ("Nick Vlahos",        "Honest Company"),
    ("Christopher Gallant","Chamberlain Coffee"),
    ("Mark Gillett",       "Gymshark"),
    ("David Butler",       "HeyDude"),
    ("Luke Wood",          "Beats"),
    ("Ricky Silver",       "Daily Harvest"),
    ("Heidi Dorosin",      "SmartSweets"),
    ("Cliff Moskowitz",    "Outdoor Voices"),
    ("Cher Fuller",        "Alo Yoga"),
    ("Peter Attia",        "David Protein"),
    ("Katie Sheeran",      "Parachute"),
    ("Stephen Kaplan",     "DECIEM"),
    ("Manish Joneja",      "BarkBox"),
]

_CONVICTION = [
    ("Brynn Putnam",          "Mirror"),
    ("Peter Rahal",           "RxBar"),
    ("Gail Becker",           "CAULIPOWER"),
    ("Kara Goldin",           "Hint Water"),
    ("Blake Mycoskie",        "TOMS"),
    ("Andy Dunn",             "Bonobos"),
    ("Seth Goldman",          "Honest Tea"),
    ("Josh Tetrick",          "JUST"),
    ("Ben McKean",            "Hungryroot"),
    ("Mark Samuel",           "Lemon Perfect"),
    ("Jeff Raider",           "Harry's"),
    ("Andy Katz-Mayfield",    "Harry's"),
    ("Neil Blumenthal",       "Warby Parker"),
    ("Dave Gilboa",           "Warby Parker"),
    ("Mark Lynn",             "care/of"),
    ("Craig Elbert",          "care/of"),
    ("Emily Weiss",           "Glossier"),
    ("Mike Cessario",         "Liquid Death"),
    ("Jing Gao",              "Fly by Jing"),
    ("Katy Hearn",            "Alani Nu"),
    ("Ben Goodwin",           "Olipop"),
    ("David Lester",          "Olipop"),
    ("Andrew Dudum",          "Hims"),
    ("Ariel Kaye",            "Parachute"),
    ("Jennifer Hyman",        "Rent the Runway"),
    ("Katrina Lake",          "Stitch Fix"),
    ("Nathan Puksta",         "Filament"),
    ("Nick Green",            "Thrive Market"),
    ("Greg Sewitz",           "Magic Spoon"),
    ("Gabi Lewis",            "Magic Spoon"),
    ("Charlotte Tilbury",     "Charlotte Tilbury"),
    ("Renaldo Webb",          "Wild One"),
    ("Steph Korey",           "Away"),
    ("Jen Rubio",             "Away"),
    ("Tyler Haney",           "Outdoor Voices"),
    ("Rachel Drori",          "Daily Harvest"),
    ("Nick Taranto",          "Plated"),
    ("Josh Hix",              "Plated"),
    ("Katia Beauchamp",       "Birchbox"),
    ("Hayley Barna",          "Birchbox"),
    ("Morgan Hermand-Waiche", "Adore Me"),
    ("Jon Sebastiani",        "KRAVE Jerky"),
    ("Philip Krim",           "Casper"),
    ("Jeff Chapin",           "Casper"),
    ("Sophia Amoruso",        "Nasty Gal"),
    ("Sasha Plavsic",         "ILIA Beauty"),
    ("Jesse Merrill",         "Good Culture"),
    ("Gabby Slome",           "Ollie"),
    ("Ryan Babenzien",        "JOLIE"),
    ("Henry Davis",           "Glossier"),
    ("Neil Parikh",           "Casper"),
    ("Luke Sherwin",          "Casper"),
    ("Jonathan Neman",        "Sweetgreen"),
    ("Nicolas Jammet",        "Sweetgreen"),
    ("Nathaniel Ru",          "Sweetgreen"),
    ("Allison Ellsworth",     "Poppi"),
    ("Stephen Ellsworth",     "Poppi"),
    ("Bill Shufelt",          "Athletic Brewing"),
    ("John Walker",           "Athletic Brewing"),
    ("Ben Francis",           "Gymshark"),
    ("Will Ahmed",            "Whoop"),
    ("Matteo Franceschetti",  "Eight Sleep"),
    ("Alexandra Zatarain",    "Eight Sleep"),
    ("Joe Kudla",             "Vuori"),
    ("Matt Meeker",           "BarkBox"),
    ("Katerina Schneider",    "Ritual"),
    ("Jordan Nathan",         "Caraway"),
    ("Ara Katz",              "Seed"),
    ("Raja Dhir",             "Seed"),
    ("Brian Rudolph",         "Banza"),
    ("Scott Rudolph",         "Banza"),
    ("Katlin Smith",          "Simple Mills"),
    ("Jessica Rolph",         "Lovevery"),
    ("Roderick Morris",       "Lovevery"),
    ("Andrew Benin",          "Graza"),
    ("Shiza Shahid",          "Our Place"),
    ("Amir Tehrani",          "Our Place"),
    ("Jordan DeCicco",        "Super Coffee"),
    ("Jake DeCicco",          "Super Coffee"),
    ("Jim DeCicco",           "Super Coffee"),
    ("Greg Davidson",         "Lalo"),
    ("Michael Wieder",        "Lalo"),
    ("Nick Saltarelli",       "Mid-Day Squares"),
    ("Jake Karls",            "Mid-Day Squares"),
    ("Kat Nouri",             "Stasher"),
    ("Mark Sisson",           "Primal Kitchen"),
    ("Jonathan Regev",        "The Farmer's Dog"),
    ("Brett Podolsky",        "The Farmer's Dog"),
    ("Pete Maldonado",        "Chomps"),
    ("Rashid Ali",            "Chomps"),
    ("Hamdi Ulukaya",         "Chobani"),
    ("David Heath",           "Bombas"),
    ("Randy Goldberg",        "Bombas"),
    ("Trina Spear",           "Figs"),
    ("Danny Winer",           "HexClad"),
    ("Cole Rubin",            "HexClad"),
    ("Joel Clark",            "Kodiak Cakes"),
    ("Jeneva Bell",           "Ruggable"),
    ("Giorgos Tsetis",        "Nutrafol"),
    ("Roland Peralta",        "Nutrafol"),
    ("Lee Mayer",             "Burrow"),
    ("Stephen Kuhl",          "Burrow"),
    ("Jonathan Shokrian",     "MeUndies"),
    ("Steven Borrelli",       "Cuts Clothing"),
    ("Mari Llewellyn",        "Bloom Nutrition"),
    ("Tara Bosch",            "SmartSweets"),
    ("Craig Dubitsky",        "Hello Products"),
    ("Adam Goldenberg",       "Fabletics"),
    ("Yael Aflalo",           "Reformation"),
    ("Rich Fulop",            "Brooklinen"),
    ("Vicki Fulop",           "Brooklinen"),
    ("Simon Enever",          "Quip"),
    ("Amanda Chantal Bacon",  "Moon Juice"),
    ("Paul Tran",             "Manscaped"),
    ("Aamir Baig",            "Article"),
    ("Andy Prochazka",        "Article"),
    ("Freddy Ward",           "Wild"),
    ("Charlie Bowes-Lyon",    "Wild"),
    ("Brandin Cohen",         "Liquid I.V."),
    ("Garrett Waggoner",      "Cirkul"),
    ("William Hicks",         "Magic Mind"),
    ("John Foraker",          "Once Upon a Farm"),
    ("Emma Chamberlain",      "Chamberlain Coffee"),
]

_ALUMNI = [
    ("Bryan Mahoney",        "Glossier"),
    ("Robin Arzón",          "Peloton"),
    ("Selby Drummond",       "Away"),
    ("Natalie Holloway",     "Bala"),
    ("Max Kislevitz",        "Bala"),
    ("Jaclyn Johnson",       "Create & Cultivate"),
    ("Amanda Goetz",         "House of Wise"),
    ("Martin Hoffmann",      "On Running"),
    ("Marc Maurer",          "On Running"),
    ("David Allemann",       "On Running"),
    ("Caspar Coppetti",      "On Running"),
    ("Kyle Leahy",           "Glossier"),
    ("Nikki Neuburger",      "Glossier"),
    ("Julie Bowerman",       "Glossier"),
    ("Colin Walsh",          "Glossier"),
    ("Chris Hall",           "Poppi"),
    ("Rohan Oza",            "Poppi"),
    ("Steve Hewitt",         "Gymshark"),
    ("Mat Dunn",             "Gymshark"),
    ("Noel Mack",            "Gymshark"),
    ("Mark Gillett",         "Gymshark"),
    ("Hillary Super",        "Savage X Fenty"),
    ("Christiane Pendarvis", "Savage X Fenty"),
    ("Terence Reilly",       "HeyDude"),
    ("David Butler",         "HeyDude"),
    ("Scott Friedman",       "Rare Beauty"),
    ("Katie Welch",          "Rare Beauty"),
    ("Jason LaRose",         "Bombas"),
    ("Nicola Kilner",        "DECIEM"),
    ("Monty Sharma",         "Therabody"),
    ("Nick Vlahos",          "Honest Company"),
    ("John Shea",            "Liquid Death"),
    ("Nancy Green",          "Athleta"),
    ("Sally Gilligan",       "Athleta"),
    ("Ricky Silver",         "Daily Harvest"),
    ("Jason Goldberger",     "Dollar Shave Club"),
    ("Heidi Dorosin",        "SmartSweets"),
    ("Morgan Zanotti",       "Primal Kitchen"),
    ("Krishna Kaliannan",    "Catalina Crunch"),
    ("Tyler Ricks",          "Super Coffee"),
    ("Nina Fuhrman",         "Moon Juice"),
    ("Fernando Machado",     "NotCo"),
]

_EXECS = [
    ("Scott Maguire",           "On Running"),
    ("Frank Sluis",             "On Running"),
    ("Olivier Bernhard",        "On Running"),
    ("Danny Harris",            "Alo Yoga"),
    ("Marco DeGeorge",          "Alo Yoga"),
    ("Karen Peters",            "Alo Yoga"),
    ("John Fieldly",            "Celsius"),
    ("Eric Hanson",             "Celsius"),
    ("Jarrod Langhans",         "Celsius"),
    ("Kevin Burns",             "Chobani"),
    ("Tarkan Gürkan",           "Chobani"),
    ("Niel Sandfort",           "Chobani"),
    ("Sumit Singh",             "Chewy"),
    ("Chris Deppe",             "Chewy"),
    ("Scott Anderson",          "Chewy"),
    ("Peter Stern",             "Peloton"),
    ("Sid Thacker",             "Peloton"),
    ("Nick Caldwell",           "Peloton"),
    ("Tarang Amin",             "e.l.f. Beauty"),
    ("Mandy Fields",            "e.l.f. Beauty"),
    ("Kory Marchisotto",        "e.l.f. Beauty"),
    ("Adrian Mitchell",         "Warby Parker"),
    ("Kim Nemser",              "Warby Parker"),
    ("Federico Muyshondt",      "BodyArmor"),
    ("Sabrina Niland",          "BodyArmor"),
    ("Ashley Kechter",          "Vuori"),
    ("Desiree Swanson",         "Vuori"),
    ("Tom Hale",                "Oura"),
    ("Sean Brecker",            "Oura"),
    ("Holly Shelton",           "Oura"),
    ("Daniel Calderoni",        "Kind Snacks"),
    ("Jon Craig",               "Kind Snacks"),
    ("Meera Bhatia",            "Fabletics"),
    ("Sue Collyns",             "Fabletics"),
    ("Sarah Oughtred",          "Figs"),
    ("Steve Berube",            "Figs"),
    ("Joe Vernachio",           "Allbirds"),
    ("Joey Zwillinger",         "Allbirds"),
    ("Jens Grede",              "Skims"),
    ("Gary Schoenfeld",         "Skims"),
    ("Michener Chandlee",       "Whoop"),
    ("Garrett Bastable",        "Whoop"),
    ("John Capodilupo",         "Whoop"),
    ("Benjamin Nazarian",       "Therabody"),
    ("Natalie Guzman",          "Savage X Fenty"),
    ("Mike Reiter",             "HeyDude"),
    ("Joyce Kim",               "Rare Beauty"),
    ("Kate Hassenfeld",         "Bombas"),
    ("Nicola Kilner",           "DECIEM"),
    ("Zahir Ibrahim",           "BarkBox"),
    ("Lindsay Liebman",         "BarkBox"),
    ("Matias Muchnick",         "NotCo"),
    ("Karim Pichara",           "NotCo"),
    ("Monica Royer",            "Ruggable"),
    ("Scott Baldassari",        "Magic Spoon"),
    ("Carla Vernón",            "Honest Company"),
    ("Eric Hohl",               "Harry's"),
    ("Andy Pearson",            "Liquid Death"),
    ("Dan Murphy",              "Liquid Death"),
    ("Michael Kim",             "The Farmer's Dog"),
    ("Jennifer Bremner",        "The Farmer's Dog"),
    ("Damian Hopkins",          "Gymshark"),
    ("Dan D'Agostino",          "Chomps"),
    ("Susan Senecal",           "Athletic Brewing"),
    ("Michael Dubin",           "Dollar Shave Club"),
    ("Tom Bilyeu",              "Quest Nutrition"),
    ("Ron Penna",               "Quest Nutrition"),
    ("Kat Cole",                "AG1"),
    ("Chris Ashenden",          "AG1"),
    ("Andy Gay",                "Cirkul"),
    ("Jenny Ming",              "Rothy's"),
    ("Stephen Hawthornthwaite", "Rothy's"),
    ("Massimo Esposito",        "Eight Sleep"),
    ("Lindsay Jang",            "Article"),
    ("Bess Weatherman",         "Nom Nom"),
    ("Ryan Bartlett",           "True Classic"),
    ("Matt Winnick",            "True Classic"),
    ("Scott Grinker",           "HexClad"),
    ("Nat Noone",               "Ritual"),
    ("Cindy Gustafson",         "Nutrafol"),
    ("Adam Sager",              "Nutrafol"),
    ("Val Oswalt",              "Kodiak Cakes"),
    ("Hali Borenstein",         "Reformation"),
    ("Bill May",                "Quip"),
    ("Sean Leary",              "Lovevery"),
    ("Janelle Strauss",         "Simple Mills"),
    ("Julian Hearn",            "Huel"),
    ("James McMaster",          "Huel"),
    ("Mark Reinstra",           "Banza"),
    ("Mike Keech",              "Liquid I.V."),
    ("Cassandra Curtis",        "Once Upon a Farm"),
    ("Jason Worrel",            "Our Place"),
    ("Doug Behrens",            "Catalina Crunch"),
    ("Sarah Van Houten",        "Catalina Crunch"),
    ("Zach Ranen",              "David Protein"),
    ("Bryan Lalezarian",        "MeUndies"),
    ("Mehdi Oufkir",            "Parachute"),
    ("Sean Christman",          "Cuts Clothing"),
    ("Anisha Raghavan",         "Seed"),
    ("Katrina Hahn",            "SmartSweets"),
    ("Rachel Prescott",         "Caraway"),
    ("Diana Haussling",         "Hello Products"),
    ("Gustav Hossy",            "Chamberlain Coffee"),
    ("Elsie Rutterford",        "Wild"),
    ("Allen Dushi",             "Graza"),
    ("Gabrielle Conforti",      "Outdoor Voices"),
    ("Rob Webb",                "Magic Mind"),
    ("Bill Keith",              "Perfect Bar"),
    ("Leigh Keith",             "Perfect Bar"),
    ("Kabeer Chopra",           "Burrow"),
    ("Federico Troiani",        "Moon Juice"),
    ("Jen Kelly",               "Lalo"),
    ("Lezlie Karls",            "Mid-Day Squares"),
    ("Ana Goettsch",            "Primal Kitchen"),
    ("Catherine Cu",            "Cocofloss"),
    ("Chrystle Cu",             "Cocofloss"),
    ("Moiz Ali",                "Native"),
    ("Mike Natenshon",          "Marine Layer"),
    ("Lucas Braun",             "Manscaped"),
]

# Tier priority for dedup: first appearance wins (DEPARTURE > CONVICTION > ALUMNI > EXEC)
_TIER_PRIORITY = {"DEPARTURE": 0, "CONVICTION": 1, "ALUMNI": 2, "EXEC": 3}

_ALL_TIERS_RAW = (
    [{"name": n, "brand": b, "tier": "DEPARTURE"} for n, b in _DEPARTURES] +
    [{"name": n, "brand": b, "tier": "CONVICTION"} for n, b in _CONVICTION] +
    [{"name": n, "brand": b, "tier": "ALUMNI"}     for n, b in _ALUMNI]     +
    [{"name": n, "brand": b, "tier": "EXEC"}       for n, b in _EXECS]
)

# Build deduplicated list once at import time
_seen: dict = {}
_PEOPLE_DEDUPED: list = []
for _p in _ALL_TIERS_RAW:
    _key = _p["name"].strip().lower()
    if _key not in _seen:
        _seen[_key] = len(_PEOPLE_DEDUPED)
        _PEOPLE_DEDUPED.append(_p)
    else:
        # Keep the higher-priority tier entry
        existing = _PEOPLE_DEDUPED[_seen[_key]]
        if _TIER_PRIORITY.get(_p["tier"], 99) < _TIER_PRIORITY.get(existing["tier"], 99):
            _PEOPLE_DEDUPED[_seen[_key]] = _p


def get_poll_people(tiers: list = None) -> list:
    """
    Return the deduplicated list of people to poll.
    tiers: optional filter, e.g. ["DEPARTURE", "CONVICTION", "ALUMNI"] to exclude EXECs.
    Each entry: {"name": str, "brand": str, "tier": str}
    """
    if tiers:
        return [p for p in _PEOPLE_DEDUPED if p["tier"] in tiers]
    return list(_PEOPLE_DEDUPED)


def count_by_tier() -> dict:
    """Return a dict of {tier: count} for the full deduplicated list."""
    counts: dict = {}
    for p in _PEOPLE_DEDUPED:
        counts[p["tier"]] = counts.get(p["tier"], 0) + 1
    return counts
