"""add founder_profiles table

Revision ID: 255d89da1e36
Revises: d4e5f6a7b8c9
Create Date: 2026-06-17 15:09:12.859706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '255d89da1e36'
down_revision = 'd4e5f6a7b8c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('founder_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('known_brand', sa.String(length=200), nullable=True),
    sa.Column('tier', sa.String(length=20), nullable=True),
    sa.Column('current_company', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('profile_url', sa.String(length=500), nullable=True),
    sa.Column('schools', sa.JSON(), nullable=True),
    sa.Column('past_companies', sa.JSON(), nullable=True),
    sa.Column('follower_count', sa.Integer(), nullable=True),
    sa.Column('x_handle', sa.String(length=100), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('founder_profiles')
    # ### end Alembic commands ###
