"""add scheduled_scans table

Revision ID: 3a6fdf87a1da
Revises: 18ae20aef73d
Create Date: 2026-03-21 09:49:45.201621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a6fdf87a1da'
down_revision = '18ae20aef73d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('days_back', sa.Integer(), nullable=True),
    sa.Column('max_results', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_new', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scheduled_scans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduled_scans_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_scans_owner_id'))

    op.drop_table('scheduled_scans')
    # ### end Alembic commands ###
