"""add outreach CRM fields to founder_profiles

Revision ID: 648f88c8e46e
Revises: 255d89da1e36
Create Date: 2026-06-17 17:59:47.742991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '648f88c8e46e'
down_revision = '255d89da1e36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('founder_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('outreach_status', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('outreach_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('last_contact', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('next_action', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('founder_profiles', schema=None) as batch_op:
        batch_op.drop_column('next_action')
        batch_op.drop_column('last_contact')
        batch_op.drop_column('outreach_notes')
        batch_op.drop_column('outreach_status')

    # ### end Alembic commands ###
